"""
SpendWise Backend Setup Helper
================================
Run this ONCE after you have your Supabase database URL to:
  1. Update your .env with the correct DATABASE_URL
  2. Install psycopg2-binary (needed for Alembic)
  3. Run Alembic migrations (creates all tables)
  4. Seed default categories

Usage:
    python setup_db.py

You will be prompted to enter your Supabase connection string.
"""
import os
import sys
import subprocess

BANNER = """
╔══════════════════════════════════════════════════════════╗
║         SpendWise — Database Setup Wizard               ║
╚══════════════════════════════════════════════════════════╝
"""

print(BANNER)
print("📋 You need your Supabase database connection string.")
print("   Go to: https://supabase.com/dashboard → Your project → Settings → Database")
print("   Scroll to 'Connection string' → Mode: URI → Copy it.\n")
print("   It looks like:")
print("   postgresql://postgres.xxxx:[PASSWORD]@aws-0-ap-south-1.pooler.supabase.com:5432/postgres\n")

raw_url = input("🔗 Paste your Supabase connection URI here: ").strip()

if not raw_url.startswith("postgresql"):
    print("❌ That doesn't look like a valid PostgreSQL URI. Please check and try again.")
    sys.exit(1)

# Convert to asyncpg format for the app
if raw_url.startswith("postgresql://"):
    async_url = raw_url.replace("postgresql://", "postgresql+asyncpg://", 1)
elif raw_url.startswith("postgresql+asyncpg://"):
    async_url = raw_url
else:
    async_url = raw_url

# sync URL for Alembic
sync_url = async_url.replace("postgresql+asyncpg://", "postgresql+psycopg2://", 1)

print(f"\n✅ Async URL (for app):    {async_url[:60]}...")
print(f"✅ Sync  URL (for alembic): {sync_url[:60]}...")

# Write .env file
env_content = f"""# SpendWise Backend — Development .env
# Generated by setup_db.py

DATABASE_URL={async_url}
SECRET_KEY=dev-secret-key-replace-with-openssl-rand-hex-32-in-production
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=10080
ALLOWED_ORIGINS=["http://localhost:5173","http://localhost:3000"]
ENV=development
"""

env_path = os.path.join(os.path.dirname(__file__), ".env")
with open(env_path, "w") as f:
    f.write(env_content)
print(f"\n📝 Written to {env_path}")

# Install psycopg2-binary
print("\n📦 Installing psycopg2-binary for Alembic migrations...")
subprocess.run([sys.executable, "-m", "pip", "install", "psycopg2-binary==2.9.10"], check=True)

# Run Alembic migrations
print("\n🔄 Running Alembic migrations (creating all tables)...")
result = subprocess.run(
    [sys.executable, "-m", "alembic", "upgrade", "head"],
    cwd=os.path.dirname(__file__),
    capture_output=False,
)
if result.returncode != 0:
    print("\n❌ Migration failed! Check the error above.")
    sys.exit(1)
print("✅ All tables created!")

# Run seed
print("\n🌱 Seeding default categories...")
result = subprocess.run(
    [sys.executable, "seed.py"],
    cwd=os.path.dirname(__file__),
    capture_output=False,
)
if result.returncode != 0:
    print("\n⚠️  Seed may have failed. Check above for errors.")
else:
    print("✅ Default categories seeded!")

print("""
╔══════════════════════════════════════════════════════════╗
║  ✅ Setup Complete! Now run:                            ║
║                                                          ║
║     .\\venv\\Scripts\\activate                             ║
║     uvicorn app.main:app --reload                        ║
║                                                          ║
║  Then open: http://localhost:5173 and sign up!          ║
╚══════════════════════════════════════════════════════════╝
""")
